repos:
  - repo: https://github.com/jan9103/pre-commit-nushell
    rev: v0.1
    hooks:
      - id: check-nu-ast
        exclude: 'packer_api\.nu' # ast does not understand relative imports
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
